name: Docker Image CI
on:
  release:
    types: [published]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish microfunctions-serverless
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: microfunctions/microfunctions-serverless
          username: ${{ secrets.LOGIN_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}
          tag_names: true

